export const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_REQUEST: 'REQUEST',
    LOGIN: 'LOGIN',
    LOGIN_ERROR: 'ERROR',
    LOGOUT: 'LOGOUT',
    CHANGE_NAME: 'CHANGE_NAME',

    REGISTRATION: 'REGISTRATION',
    REGISTRATION_REQUEST: 'REGISTRATION_REQUEST',
    REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
    REGISTRATION_ERROR: 'REGISTRATION_ERROR'
};